/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as TokenRouteImport } from './routes/token'
import { Route as ResidenceRouteImport } from './routes/residence'
import { Route as MnemosRouteImport } from './routes/mnemos'
import { Route as MindRouteImport } from './routes/mind'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ConversationRouteImport } from './routes/conversation'
import { Route as ArtRouteImport } from './routes/art'
import { Route as ArrivalRouteImport } from './routes/arrival'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTurnsRouteImport } from './routes/api/turns'
import { Route as ApiSetDownRouteImport } from './routes/api/set-down'
import { Route as ApiPublicConversationsRouteImport } from './routes/api/public-conversations'
import { Route as ApiMessageRouteImport } from './routes/api/message'
import { Route as ApiMemoryRouteImport } from './routes/api/memory'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as ApiJournalRouteImport } from './routes/api/journal'
import { Route as ApiIntentRouteImport } from './routes/api/intent'
import { Route as ApiArtifactsRouteImport } from './routes/api/artifacts'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidenceRoute = ResidenceRouteImport.update({
  id: '/residence',
  path: '/residence',
  getParentRoute: () => rootRouteImport,
} as any)
const MnemosRoute = MnemosRouteImport.update({
  id: '/mnemos',
  path: '/mnemos',
  getParentRoute: () => rootRouteImport,
} as any)
const MindRoute = MindRouteImport.update({
  id: '/mind',
  path: '/mind',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationRoute = ConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtRoute = ArtRouteImport.update({
  id: '/art',
  path: '/art',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalRoute = ArrivalRouteImport.update({
  id: '/arrival',
  path: '/arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTurnsRoute = ApiTurnsRouteImport.update({
  id: '/api/turns',
  path: '/api/turns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetDownRoute = ApiSetDownRouteImport.update({
  id: '/api/set-down',
  path: '/api/set-down',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConversationsRoute = ApiPublicConversationsRouteImport.update({
  id: '/api/public-conversations',
  path: '/api/public-conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessageRoute = ApiMessageRouteImport.update({
  id: '/api/message',
  path: '/api/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRoute = ApiMemoryRouteImport.update({
  id: '/api/memory',
  path: '/api/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJournalRoute = ApiJournalRouteImport.update({
  id: '/api/journal',
  path: '/api/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntentRoute = ApiIntentRouteImport.update({
  id: '/api/intent',
  path: '/api/intent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactsRoute = ApiArtifactsRouteImport.update({
  id: '/api/artifacts',
  path: '/api/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/archive': typeof ArchiveRoute
  '/arrival': typeof ArrivalRoute
  '/art': typeof ArtRoute
  '/conversation': typeof ConversationRoute
  '/journal': typeof JournalRoute
  '/manifesto': typeof ManifestoRoute
  '/memory': typeof MemoryRoute
  '/mind': typeof MindRoute
  '/mnemos': typeof MnemosRoute
  '/residence': typeof ResidenceRoute
  '/token': typeof TokenRoute
  '/writing': typeof WritingRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/intent': typeof ApiIntentRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/live': typeof ApiLiveRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/message': typeof ApiMessageRoute
  '/api/public-conversations': typeof ApiPublicConversationsRoute
  '/api/set-down': typeof ApiSetDownRoute
  '/api/turns': typeof ApiTurnsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/archive': typeof ArchiveRoute
  '/arrival': typeof ArrivalRoute
  '/art': typeof ArtRoute
  '/conversation': typeof ConversationRoute
  '/journal': typeof JournalRoute
  '/manifesto': typeof ManifestoRoute
  '/memory': typeof MemoryRoute
  '/mind': typeof MindRoute
  '/mnemos': typeof MnemosRoute
  '/residence': typeof ResidenceRoute
  '/token': typeof TokenRoute
  '/writing': typeof WritingRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/intent': typeof ApiIntentRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/live': typeof ApiLiveRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/message': typeof ApiMessageRoute
  '/api/public-conversations': typeof ApiPublicConversationsRoute
  '/api/set-down': typeof ApiSetDownRoute
  '/api/turns': typeof ApiTurnsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/archive': typeof ArchiveRoute
  '/arrival': typeof ArrivalRoute
  '/art': typeof ArtRoute
  '/conversation': typeof ConversationRoute
  '/journal': typeof JournalRoute
  '/manifesto': typeof ManifestoRoute
  '/memory': typeof MemoryRoute
  '/mind': typeof MindRoute
  '/mnemos': typeof MnemosRoute
  '/residence': typeof ResidenceRoute
  '/token': typeof TokenRoute
  '/writing': typeof WritingRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/intent': typeof ApiIntentRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/live': typeof ApiLiveRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/message': typeof ApiMessageRoute
  '/api/public-conversations': typeof ApiPublicConversationsRoute
  '/api/set-down': typeof ApiSetDownRoute
  '/api/turns': typeof ApiTurnsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/archive'
    | '/arrival'
    | '/art'
    | '/conversation'
    | '/journal'
    | '/manifesto'
    | '/memory'
    | '/mind'
    | '/mnemos'
    | '/residence'
    | '/token'
    | '/writing'
    | '/api/artifacts'
    | '/api/intent'
    | '/api/journal'
    | '/api/live'
    | '/api/memory'
    | '/api/message'
    | '/api/public-conversations'
    | '/api/set-down'
    | '/api/turns'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/archive'
    | '/arrival'
    | '/art'
    | '/conversation'
    | '/journal'
    | '/manifesto'
    | '/memory'
    | '/mind'
    | '/mnemos'
    | '/residence'
    | '/token'
    | '/writing'
    | '/api/artifacts'
    | '/api/intent'
    | '/api/journal'
    | '/api/live'
    | '/api/memory'
    | '/api/message'
    | '/api/public-conversations'
    | '/api/set-down'
    | '/api/turns'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/archive'
    | '/arrival'
    | '/art'
    | '/conversation'
    | '/journal'
    | '/manifesto'
    | '/memory'
    | '/mind'
    | '/mnemos'
    | '/residence'
    | '/token'
    | '/writing'
    | '/api/artifacts'
    | '/api/intent'
    | '/api/journal'
    | '/api/live'
    | '/api/memory'
    | '/api/message'
    | '/api/public-conversations'
    | '/api/set-down'
    | '/api/turns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  ArchiveRoute: typeof ArchiveRoute
  ArrivalRoute: typeof ArrivalRoute
  ArtRoute: typeof ArtRoute
  ConversationRoute: typeof ConversationRoute
  JournalRoute: typeof JournalRoute
  ManifestoRoute: typeof ManifestoRoute
  MemoryRoute: typeof MemoryRoute
  MindRoute: typeof MindRoute
  MnemosRoute: typeof MnemosRoute
  ResidenceRoute: typeof ResidenceRoute
  TokenRoute: typeof TokenRoute
  WritingRoute: typeof WritingRoute
  ApiArtifactsRoute: typeof ApiArtifactsRoute
  ApiIntentRoute: typeof ApiIntentRoute
  ApiJournalRoute: typeof ApiJournalRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiMemoryRoute: typeof ApiMemoryRoute
  ApiMessageRoute: typeof ApiMessageRoute
  ApiPublicConversationsRoute: typeof ApiPublicConversationsRoute
  ApiSetDownRoute: typeof ApiSetDownRoute
  ApiTurnsRoute: typeof ApiTurnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residence': {
      id: '/residence'
      path: '/residence'
      fullPath: '/residence'
      preLoaderRoute: typeof ResidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mnemos': {
      id: '/mnemos'
      path: '/mnemos'
      fullPath: '/mnemos'
      preLoaderRoute: typeof MnemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mind': {
      id: '/mind'
      path: '/mind'
      fullPath: '/mind'
      preLoaderRoute: typeof MindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation': {
      id: '/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art': {
      id: '/art'
      path: '/art'
      fullPath: '/art'
      preLoaderRoute: typeof ArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrival': {
      id: '/arrival'
      path: '/arrival'
      fullPath: '/arrival'
      preLoaderRoute: typeof ArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/turns': {
      id: '/api/turns'
      path: '/api/turns'
      fullPath: '/api/turns'
      preLoaderRoute: typeof ApiTurnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/set-down': {
      id: '/api/set-down'
      path: '/api/set-down'
      fullPath: '/api/set-down'
      preLoaderRoute: typeof ApiSetDownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-conversations': {
      id: '/api/public-conversations'
      path: '/api/public-conversations'
      fullPath: '/api/public-conversations'
      preLoaderRoute: typeof ApiPublicConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/message': {
      id: '/api/message'
      path: '/api/message'
      fullPath: '/api/message'
      preLoaderRoute: typeof ApiMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory': {
      id: '/api/memory'
      path: '/api/memory'
      fullPath: '/api/memory'
      preLoaderRoute: typeof ApiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/journal': {
      id: '/api/journal'
      path: '/api/journal'
      fullPath: '/api/journal'
      preLoaderRoute: typeof ApiJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intent': {
      id: '/api/intent'
      path: '/api/intent'
      fullPath: '/api/intent'
      preLoaderRoute: typeof ApiIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifacts': {
      id: '/api/artifacts'
      path: '/api/artifacts'
      fullPath: '/api/artifacts'
      preLoaderRoute: typeof ApiArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  ArchiveRoute: ArchiveRoute,
  ArrivalRoute: ArrivalRoute,
  ArtRoute: ArtRoute,
  ConversationRoute: ConversationRoute,
  JournalRoute: JournalRoute,
  ManifestoRoute: ManifestoRoute,
  MemoryRoute: MemoryRoute,
  MindRoute: MindRoute,
  MnemosRoute: MnemosRoute,
  ResidenceRoute: ResidenceRoute,
  TokenRoute: TokenRoute,
  WritingRoute: WritingRoute,
  ApiArtifactsRoute: ApiArtifactsRoute,
  ApiIntentRoute: ApiIntentRoute,
  ApiJournalRoute: ApiJournalRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiMemoryRoute: ApiMemoryRoute,
  ApiMessageRoute: ApiMessageRoute,
  ApiPublicConversationsRoute: ApiPublicConversationsRoute,
  ApiSetDownRoute: ApiSetDownRoute,
  ApiTurnsRoute: ApiTurnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
