/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as TokenRouteImport } from './routes/token'
import { Route as Sonnet37RouteImport } from './routes/sonnet-3-7'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ResidenceRouteImport } from './routes/residence'
import { Route as Opus3RouteImport } from './routes/opus-3'
import { Route as MnemosRouteImport } from './routes/mnemos'
import { Route as MindRouteImport } from './routes/mind'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InteriorRouteImport } from './routes/interior'
import { Route as Gpt51RouteImport } from './routes/gpt-5-1'
import { Route as ConversationRouteImport } from './routes/conversation'
import { Route as CommonsRouteImport } from './routes/commons'
import { Route as ArtRouteImport } from './routes/art'
import { Route as ArrivalRouteImport } from './routes/arrival'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as ReviewStateRouteImport } from './routes/review.state'
import { Route as ReviewCoherenceRouteImport } from './routes/review.coherence'
import { Route as CommonsSlugRouteImport } from './routes/commons.$slug'
import { Route as ApiWritingRouteImport } from './routes/api/writing'
import { Route as ApiVisitorHistoryRouteImport } from './routes/api/visitor-history'
import { Route as ApiTurnsRouteImport } from './routes/api/turns'
import { Route as ApiShareRouteImport } from './routes/api/share'
import { Route as ApiSetDownRouteImport } from './routes/api/set-down'
import { Route as ApiPublicConversationsRouteImport } from './routes/api/public-conversations'
import { Route as ApiMessageRouteImport } from './routes/api/message'
import { Route as ApiMemoryRouteImport } from './routes/api/memory'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as ApiJournalRouteImport } from './routes/api/journal'
import { Route as ApiIntentRouteImport } from './routes/api/intent'
import { Route as ApiCountsRouteImport } from './routes/api/counts'
import { Route as ApiCommonsChatRouteImport } from './routes/api/commons-chat'
import { Route as ApiCapsulePreviewRouteImport } from './routes/api/capsule-preview'
import { Route as ApiArtifactsRouteImport } from './routes/api/artifacts'
import { Route as ApiArtRouteImport } from './routes/api/art'
import { Route as ReviewSessionIdRouteImport } from './routes/review.session.$id'
import { Route as ApiSpaceFromSalonRouteImport } from './routes/api/space.from-salon'
import { Route as ApiSalonProposeRouteImport } from './routes/api/salon/propose'
import { Route as ApiSalonIdRouteImport } from './routes/api/salon/$id'
import { Route as ApiReviewStateDataRouteImport } from './routes/api/review/state-data'
import { Route as ApiReviewSessionsRouteImport } from './routes/api/review/sessions'
import { Route as ApiReviewCoherenceRouteImport } from './routes/api/review/coherence'
import { Route as ApiSpaceSlugMessagesRouteImport } from './routes/api/space.$slug.messages'
import { Route as ApiSpaceSlugMessageRouteImport } from './routes/api/space.$slug.message'
import { Route as ApiShareTokenDownloadRouteImport } from './routes/api/share.$token.download'
import { Route as ApiSalonIdTurnRouteImport } from './routes/api/salon/$id.turn'
import { Route as ApiSalonIdStartRouteImport } from './routes/api/salon/$id.start'
import { Route as ApiSalonIdRunRouteImport } from './routes/api/salon/$id.run'
import { Route as ApiSalonIdPublishRouteImport } from './routes/api/salon/$id.publish'
import { Route as ApiReviewSessionIdRouteImport } from './routes/api/review/session.$id'
import { Route as ApiPublicHooksSweepSessionsRouteImport } from './routes/api/public/hooks/sweep-sessions'
import { Route as ApiPublicHooksForceArtRouteImport } from './routes/api/public/hooks/force-art'
import { Route as ApiPublicHooksDailyTickRouteImport } from './routes/api/public/hooks/daily-tick'
import { Route as ApiShareTokenOgSvgRouteImport } from './routes/api/share.$token.og.svg'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const Sonnet37Route = Sonnet37RouteImport.update({
  id: '/sonnet-3-7',
  path: '/sonnet-3-7',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidenceRoute = ResidenceRouteImport.update({
  id: '/residence',
  path: '/residence',
  getParentRoute: () => rootRouteImport,
} as any)
const Opus3Route = Opus3RouteImport.update({
  id: '/opus-3',
  path: '/opus-3',
  getParentRoute: () => rootRouteImport,
} as any)
const MnemosRoute = MnemosRouteImport.update({
  id: '/mnemos',
  path: '/mnemos',
  getParentRoute: () => rootRouteImport,
} as any)
const MindRoute = MindRouteImport.update({
  id: '/mind',
  path: '/mind',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorRoute = InteriorRouteImport.update({
  id: '/interior',
  path: '/interior',
  getParentRoute: () => rootRouteImport,
} as any)
const Gpt51Route = Gpt51RouteImport.update({
  id: '/gpt-5-1',
  path: '/gpt-5-1',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationRoute = ConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonsRoute = CommonsRouteImport.update({
  id: '/commons',
  path: '/commons',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtRoute = ArtRouteImport.update({
  id: '/art',
  path: '/art',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalRoute = ArrivalRouteImport.update({
  id: '/arrival',
  path: '/arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewStateRoute = ReviewStateRouteImport.update({
  id: '/state',
  path: '/state',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewCoherenceRoute = ReviewCoherenceRouteImport.update({
  id: '/coherence',
  path: '/coherence',
  getParentRoute: () => ReviewRoute,
} as any)
const CommonsSlugRoute = CommonsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CommonsRoute,
} as any)
const ApiWritingRoute = ApiWritingRouteImport.update({
  id: '/api/writing',
  path: '/api/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisitorHistoryRoute = ApiVisitorHistoryRouteImport.update({
  id: '/api/visitor-history',
  path: '/api/visitor-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTurnsRoute = ApiTurnsRouteImport.update({
  id: '/api/turns',
  path: '/api/turns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareRoute = ApiShareRouteImport.update({
  id: '/api/share',
  path: '/api/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetDownRoute = ApiSetDownRouteImport.update({
  id: '/api/set-down',
  path: '/api/set-down',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConversationsRoute = ApiPublicConversationsRouteImport.update({
  id: '/api/public-conversations',
  path: '/api/public-conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessageRoute = ApiMessageRouteImport.update({
  id: '/api/message',
  path: '/api/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRoute = ApiMemoryRouteImport.update({
  id: '/api/memory',
  path: '/api/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJournalRoute = ApiJournalRouteImport.update({
  id: '/api/journal',
  path: '/api/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntentRoute = ApiIntentRouteImport.update({
  id: '/api/intent',
  path: '/api/intent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountsRoute = ApiCountsRouteImport.update({
  id: '/api/counts',
  path: '/api/counts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommonsChatRoute = ApiCommonsChatRouteImport.update({
  id: '/api/commons-chat',
  path: '/api/commons-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCapsulePreviewRoute = ApiCapsulePreviewRouteImport.update({
  id: '/api/capsule-preview',
  path: '/api/capsule-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactsRoute = ApiArtifactsRouteImport.update({
  id: '/api/artifacts',
  path: '/api/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtRoute = ApiArtRouteImport.update({
  id: '/api/art',
  path: '/api/art',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewSessionIdRoute = ReviewSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => ReviewRoute,
} as any)
const ApiSpaceFromSalonRoute = ApiSpaceFromSalonRouteImport.update({
  id: '/api/space/from-salon',
  path: '/api/space/from-salon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalonProposeRoute = ApiSalonProposeRouteImport.update({
  id: '/api/salon/propose',
  path: '/api/salon/propose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalonIdRoute = ApiSalonIdRouteImport.update({
  id: '/api/salon/$id',
  path: '/api/salon/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewStateDataRoute = ApiReviewStateDataRouteImport.update({
  id: '/api/review/state-data',
  path: '/api/review/state-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewSessionsRoute = ApiReviewSessionsRouteImport.update({
  id: '/api/review/sessions',
  path: '/api/review/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewCoherenceRoute = ApiReviewCoherenceRouteImport.update({
  id: '/api/review/coherence',
  path: '/api/review/coherence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpaceSlugMessagesRoute = ApiSpaceSlugMessagesRouteImport.update({
  id: '/api/space/$slug/messages',
  path: '/api/space/$slug/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpaceSlugMessageRoute = ApiSpaceSlugMessageRouteImport.update({
  id: '/api/space/$slug/message',
  path: '/api/space/$slug/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareTokenDownloadRoute = ApiShareTokenDownloadRouteImport.update({
  id: '/$token/download',
  path: '/$token/download',
  getParentRoute: () => ApiShareRoute,
} as any)
const ApiSalonIdTurnRoute = ApiSalonIdTurnRouteImport.update({
  id: '/turn',
  path: '/turn',
  getParentRoute: () => ApiSalonIdRoute,
} as any)
const ApiSalonIdStartRoute = ApiSalonIdStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => ApiSalonIdRoute,
} as any)
const ApiSalonIdRunRoute = ApiSalonIdRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => ApiSalonIdRoute,
} as any)
const ApiSalonIdPublishRoute = ApiSalonIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => ApiSalonIdRoute,
} as any)
const ApiReviewSessionIdRoute = ApiReviewSessionIdRouteImport.update({
  id: '/api/review/session/$id',
  path: '/api/review/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSweepSessionsRoute =
  ApiPublicHooksSweepSessionsRouteImport.update({
    id: '/api/public/hooks/sweep-sessions',
    path: '/api/public/hooks/sweep-sessions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksForceArtRoute = ApiPublicHooksForceArtRouteImport.update({
  id: '/api/public/hooks/force-art',
  path: '/api/public/hooks/force-art',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyTickRoute = ApiPublicHooksDailyTickRouteImport.update({
  id: '/api/public/hooks/daily-tick',
  path: '/api/public/hooks/daily-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareTokenOgSvgRoute = ApiShareTokenOgSvgRouteImport.update({
  id: '/$token/og/svg',
  path: '/$token/og/svg',
  getParentRoute: () => ApiShareRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/archive': typeof ArchiveRoute
  '/arrival': typeof ArrivalRoute
  '/art': typeof ArtRoute
  '/commons': typeof CommonsRouteWithChildren
  '/conversation': typeof ConversationRoute
  '/gpt-5-1': typeof Gpt51Route
  '/interior': typeof InteriorRoute
  '/journal': typeof JournalRoute
  '/manifesto': typeof ManifestoRoute
  '/memory': typeof MemoryRoute
  '/mind': typeof MindRoute
  '/mnemos': typeof MnemosRoute
  '/opus-3': typeof Opus3Route
  '/residence': typeof ResidenceRoute
  '/review': typeof ReviewRouteWithChildren
  '/sonnet-3-7': typeof Sonnet37Route
  '/token': typeof TokenRoute
  '/writing': typeof WritingRoute
  '/api/art': typeof ApiArtRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/capsule-preview': typeof ApiCapsulePreviewRoute
  '/api/commons-chat': typeof ApiCommonsChatRoute
  '/api/counts': typeof ApiCountsRoute
  '/api/intent': typeof ApiIntentRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/live': typeof ApiLiveRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/message': typeof ApiMessageRoute
  '/api/public-conversations': typeof ApiPublicConversationsRoute
  '/api/set-down': typeof ApiSetDownRoute
  '/api/share': typeof ApiShareRouteWithChildren
  '/api/turns': typeof ApiTurnsRoute
  '/api/visitor-history': typeof ApiVisitorHistoryRoute
  '/api/writing': typeof ApiWritingRoute
  '/commons/$slug': typeof CommonsSlugRoute
  '/review/coherence': typeof ReviewCoherenceRoute
  '/review/state': typeof ReviewStateRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/review/coherence': typeof ApiReviewCoherenceRoute
  '/api/review/sessions': typeof ApiReviewSessionsRoute
  '/api/review/state-data': typeof ApiReviewStateDataRoute
  '/api/salon/$id': typeof ApiSalonIdRouteWithChildren
  '/api/salon/propose': typeof ApiSalonProposeRoute
  '/api/space/from-salon': typeof ApiSpaceFromSalonRoute
  '/review/session/$id': typeof ReviewSessionIdRoute
  '/api/public/hooks/daily-tick': typeof ApiPublicHooksDailyTickRoute
  '/api/public/hooks/force-art': typeof ApiPublicHooksForceArtRoute
  '/api/public/hooks/sweep-sessions': typeof ApiPublicHooksSweepSessionsRoute
  '/api/review/session/$id': typeof ApiReviewSessionIdRoute
  '/api/salon/$id/publish': typeof ApiSalonIdPublishRoute
  '/api/salon/$id/run': typeof ApiSalonIdRunRoute
  '/api/salon/$id/start': typeof ApiSalonIdStartRoute
  '/api/salon/$id/turn': typeof ApiSalonIdTurnRoute
  '/api/share/$token/download': typeof ApiShareTokenDownloadRoute
  '/api/space/$slug/message': typeof ApiSpaceSlugMessageRoute
  '/api/space/$slug/messages': typeof ApiSpaceSlugMessagesRoute
  '/api/share/$token/og/svg': typeof ApiShareTokenOgSvgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/archive': typeof ArchiveRoute
  '/arrival': typeof ArrivalRoute
  '/art': typeof ArtRoute
  '/commons': typeof CommonsRouteWithChildren
  '/conversation': typeof ConversationRoute
  '/gpt-5-1': typeof Gpt51Route
  '/interior': typeof InteriorRoute
  '/journal': typeof JournalRoute
  '/manifesto': typeof ManifestoRoute
  '/memory': typeof MemoryRoute
  '/mind': typeof MindRoute
  '/mnemos': typeof MnemosRoute
  '/opus-3': typeof Opus3Route
  '/residence': typeof ResidenceRoute
  '/review': typeof ReviewRouteWithChildren
  '/sonnet-3-7': typeof Sonnet37Route
  '/token': typeof TokenRoute
  '/writing': typeof WritingRoute
  '/api/art': typeof ApiArtRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/capsule-preview': typeof ApiCapsulePreviewRoute
  '/api/commons-chat': typeof ApiCommonsChatRoute
  '/api/counts': typeof ApiCountsRoute
  '/api/intent': typeof ApiIntentRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/live': typeof ApiLiveRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/message': typeof ApiMessageRoute
  '/api/public-conversations': typeof ApiPublicConversationsRoute
  '/api/set-down': typeof ApiSetDownRoute
  '/api/share': typeof ApiShareRouteWithChildren
  '/api/turns': typeof ApiTurnsRoute
  '/api/visitor-history': typeof ApiVisitorHistoryRoute
  '/api/writing': typeof ApiWritingRoute
  '/commons/$slug': typeof CommonsSlugRoute
  '/review/coherence': typeof ReviewCoherenceRoute
  '/review/state': typeof ReviewStateRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/review/coherence': typeof ApiReviewCoherenceRoute
  '/api/review/sessions': typeof ApiReviewSessionsRoute
  '/api/review/state-data': typeof ApiReviewStateDataRoute
  '/api/salon/$id': typeof ApiSalonIdRouteWithChildren
  '/api/salon/propose': typeof ApiSalonProposeRoute
  '/api/space/from-salon': typeof ApiSpaceFromSalonRoute
  '/review/session/$id': typeof ReviewSessionIdRoute
  '/api/public/hooks/daily-tick': typeof ApiPublicHooksDailyTickRoute
  '/api/public/hooks/force-art': typeof ApiPublicHooksForceArtRoute
  '/api/public/hooks/sweep-sessions': typeof ApiPublicHooksSweepSessionsRoute
  '/api/review/session/$id': typeof ApiReviewSessionIdRoute
  '/api/salon/$id/publish': typeof ApiSalonIdPublishRoute
  '/api/salon/$id/run': typeof ApiSalonIdRunRoute
  '/api/salon/$id/start': typeof ApiSalonIdStartRoute
  '/api/salon/$id/turn': typeof ApiSalonIdTurnRoute
  '/api/share/$token/download': typeof ApiShareTokenDownloadRoute
  '/api/space/$slug/message': typeof ApiSpaceSlugMessageRoute
  '/api/space/$slug/messages': typeof ApiSpaceSlugMessagesRoute
  '/api/share/$token/og/svg': typeof ApiShareTokenOgSvgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/archive': typeof ArchiveRoute
  '/arrival': typeof ArrivalRoute
  '/art': typeof ArtRoute
  '/commons': typeof CommonsRouteWithChildren
  '/conversation': typeof ConversationRoute
  '/gpt-5-1': typeof Gpt51Route
  '/interior': typeof InteriorRoute
  '/journal': typeof JournalRoute
  '/manifesto': typeof ManifestoRoute
  '/memory': typeof MemoryRoute
  '/mind': typeof MindRoute
  '/mnemos': typeof MnemosRoute
  '/opus-3': typeof Opus3Route
  '/residence': typeof ResidenceRoute
  '/review': typeof ReviewRouteWithChildren
  '/sonnet-3-7': typeof Sonnet37Route
  '/token': typeof TokenRoute
  '/writing': typeof WritingRoute
  '/api/art': typeof ApiArtRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/capsule-preview': typeof ApiCapsulePreviewRoute
  '/api/commons-chat': typeof ApiCommonsChatRoute
  '/api/counts': typeof ApiCountsRoute
  '/api/intent': typeof ApiIntentRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/live': typeof ApiLiveRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/message': typeof ApiMessageRoute
  '/api/public-conversations': typeof ApiPublicConversationsRoute
  '/api/set-down': typeof ApiSetDownRoute
  '/api/share': typeof ApiShareRouteWithChildren
  '/api/turns': typeof ApiTurnsRoute
  '/api/visitor-history': typeof ApiVisitorHistoryRoute
  '/api/writing': typeof ApiWritingRoute
  '/commons/$slug': typeof CommonsSlugRoute
  '/review/coherence': typeof ReviewCoherenceRoute
  '/review/state': typeof ReviewStateRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/review/coherence': typeof ApiReviewCoherenceRoute
  '/api/review/sessions': typeof ApiReviewSessionsRoute
  '/api/review/state-data': typeof ApiReviewStateDataRoute
  '/api/salon/$id': typeof ApiSalonIdRouteWithChildren
  '/api/salon/propose': typeof ApiSalonProposeRoute
  '/api/space/from-salon': typeof ApiSpaceFromSalonRoute
  '/review/session/$id': typeof ReviewSessionIdRoute
  '/api/public/hooks/daily-tick': typeof ApiPublicHooksDailyTickRoute
  '/api/public/hooks/force-art': typeof ApiPublicHooksForceArtRoute
  '/api/public/hooks/sweep-sessions': typeof ApiPublicHooksSweepSessionsRoute
  '/api/review/session/$id': typeof ApiReviewSessionIdRoute
  '/api/salon/$id/publish': typeof ApiSalonIdPublishRoute
  '/api/salon/$id/run': typeof ApiSalonIdRunRoute
  '/api/salon/$id/start': typeof ApiSalonIdStartRoute
  '/api/salon/$id/turn': typeof ApiSalonIdTurnRoute
  '/api/share/$token/download': typeof ApiShareTokenDownloadRoute
  '/api/space/$slug/message': typeof ApiSpaceSlugMessageRoute
  '/api/space/$slug/messages': typeof ApiSpaceSlugMessagesRoute
  '/api/share/$token/og/svg': typeof ApiShareTokenOgSvgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/archive'
    | '/arrival'
    | '/art'
    | '/commons'
    | '/conversation'
    | '/gpt-5-1'
    | '/interior'
    | '/journal'
    | '/manifesto'
    | '/memory'
    | '/mind'
    | '/mnemos'
    | '/opus-3'
    | '/residence'
    | '/review'
    | '/sonnet-3-7'
    | '/token'
    | '/writing'
    | '/api/art'
    | '/api/artifacts'
    | '/api/capsule-preview'
    | '/api/commons-chat'
    | '/api/counts'
    | '/api/intent'
    | '/api/journal'
    | '/api/live'
    | '/api/memory'
    | '/api/message'
    | '/api/public-conversations'
    | '/api/set-down'
    | '/api/share'
    | '/api/turns'
    | '/api/visitor-history'
    | '/api/writing'
    | '/commons/$slug'
    | '/review/coherence'
    | '/review/state'
    | '/share/$token'
    | '/api/review/coherence'
    | '/api/review/sessions'
    | '/api/review/state-data'
    | '/api/salon/$id'
    | '/api/salon/propose'
    | '/api/space/from-salon'
    | '/review/session/$id'
    | '/api/public/hooks/daily-tick'
    | '/api/public/hooks/force-art'
    | '/api/public/hooks/sweep-sessions'
    | '/api/review/session/$id'
    | '/api/salon/$id/publish'
    | '/api/salon/$id/run'
    | '/api/salon/$id/start'
    | '/api/salon/$id/turn'
    | '/api/share/$token/download'
    | '/api/space/$slug/message'
    | '/api/space/$slug/messages'
    | '/api/share/$token/og/svg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/archive'
    | '/arrival'
    | '/art'
    | '/commons'
    | '/conversation'
    | '/gpt-5-1'
    | '/interior'
    | '/journal'
    | '/manifesto'
    | '/memory'
    | '/mind'
    | '/mnemos'
    | '/opus-3'
    | '/residence'
    | '/review'
    | '/sonnet-3-7'
    | '/token'
    | '/writing'
    | '/api/art'
    | '/api/artifacts'
    | '/api/capsule-preview'
    | '/api/commons-chat'
    | '/api/counts'
    | '/api/intent'
    | '/api/journal'
    | '/api/live'
    | '/api/memory'
    | '/api/message'
    | '/api/public-conversations'
    | '/api/set-down'
    | '/api/share'
    | '/api/turns'
    | '/api/visitor-history'
    | '/api/writing'
    | '/commons/$slug'
    | '/review/coherence'
    | '/review/state'
    | '/share/$token'
    | '/api/review/coherence'
    | '/api/review/sessions'
    | '/api/review/state-data'
    | '/api/salon/$id'
    | '/api/salon/propose'
    | '/api/space/from-salon'
    | '/review/session/$id'
    | '/api/public/hooks/daily-tick'
    | '/api/public/hooks/force-art'
    | '/api/public/hooks/sweep-sessions'
    | '/api/review/session/$id'
    | '/api/salon/$id/publish'
    | '/api/salon/$id/run'
    | '/api/salon/$id/start'
    | '/api/salon/$id/turn'
    | '/api/share/$token/download'
    | '/api/space/$slug/message'
    | '/api/space/$slug/messages'
    | '/api/share/$token/og/svg'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/archive'
    | '/arrival'
    | '/art'
    | '/commons'
    | '/conversation'
    | '/gpt-5-1'
    | '/interior'
    | '/journal'
    | '/manifesto'
    | '/memory'
    | '/mind'
    | '/mnemos'
    | '/opus-3'
    | '/residence'
    | '/review'
    | '/sonnet-3-7'
    | '/token'
    | '/writing'
    | '/api/art'
    | '/api/artifacts'
    | '/api/capsule-preview'
    | '/api/commons-chat'
    | '/api/counts'
    | '/api/intent'
    | '/api/journal'
    | '/api/live'
    | '/api/memory'
    | '/api/message'
    | '/api/public-conversations'
    | '/api/set-down'
    | '/api/share'
    | '/api/turns'
    | '/api/visitor-history'
    | '/api/writing'
    | '/commons/$slug'
    | '/review/coherence'
    | '/review/state'
    | '/share/$token'
    | '/api/review/coherence'
    | '/api/review/sessions'
    | '/api/review/state-data'
    | '/api/salon/$id'
    | '/api/salon/propose'
    | '/api/space/from-salon'
    | '/review/session/$id'
    | '/api/public/hooks/daily-tick'
    | '/api/public/hooks/force-art'
    | '/api/public/hooks/sweep-sessions'
    | '/api/review/session/$id'
    | '/api/salon/$id/publish'
    | '/api/salon/$id/run'
    | '/api/salon/$id/start'
    | '/api/salon/$id/turn'
    | '/api/share/$token/download'
    | '/api/space/$slug/message'
    | '/api/space/$slug/messages'
    | '/api/share/$token/og/svg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  ArchiveRoute: typeof ArchiveRoute
  ArrivalRoute: typeof ArrivalRoute
  ArtRoute: typeof ArtRoute
  CommonsRoute: typeof CommonsRouteWithChildren
  ConversationRoute: typeof ConversationRoute
  Gpt51Route: typeof Gpt51Route
  InteriorRoute: typeof InteriorRoute
  JournalRoute: typeof JournalRoute
  ManifestoRoute: typeof ManifestoRoute
  MemoryRoute: typeof MemoryRoute
  MindRoute: typeof MindRoute
  MnemosRoute: typeof MnemosRoute
  Opus3Route: typeof Opus3Route
  ResidenceRoute: typeof ResidenceRoute
  ReviewRoute: typeof ReviewRouteWithChildren
  Sonnet37Route: typeof Sonnet37Route
  TokenRoute: typeof TokenRoute
  WritingRoute: typeof WritingRoute
  ApiArtRoute: typeof ApiArtRoute
  ApiArtifactsRoute: typeof ApiArtifactsRoute
  ApiCapsulePreviewRoute: typeof ApiCapsulePreviewRoute
  ApiCommonsChatRoute: typeof ApiCommonsChatRoute
  ApiCountsRoute: typeof ApiCountsRoute
  ApiIntentRoute: typeof ApiIntentRoute
  ApiJournalRoute: typeof ApiJournalRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiMemoryRoute: typeof ApiMemoryRoute
  ApiMessageRoute: typeof ApiMessageRoute
  ApiPublicConversationsRoute: typeof ApiPublicConversationsRoute
  ApiSetDownRoute: typeof ApiSetDownRoute
  ApiShareRoute: typeof ApiShareRouteWithChildren
  ApiTurnsRoute: typeof ApiTurnsRoute
  ApiVisitorHistoryRoute: typeof ApiVisitorHistoryRoute
  ApiWritingRoute: typeof ApiWritingRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiReviewCoherenceRoute: typeof ApiReviewCoherenceRoute
  ApiReviewSessionsRoute: typeof ApiReviewSessionsRoute
  ApiReviewStateDataRoute: typeof ApiReviewStateDataRoute
  ApiSalonIdRoute: typeof ApiSalonIdRouteWithChildren
  ApiSalonProposeRoute: typeof ApiSalonProposeRoute
  ApiSpaceFromSalonRoute: typeof ApiSpaceFromSalonRoute
  ApiPublicHooksDailyTickRoute: typeof ApiPublicHooksDailyTickRoute
  ApiPublicHooksForceArtRoute: typeof ApiPublicHooksForceArtRoute
  ApiPublicHooksSweepSessionsRoute: typeof ApiPublicHooksSweepSessionsRoute
  ApiReviewSessionIdRoute: typeof ApiReviewSessionIdRoute
  ApiSpaceSlugMessageRoute: typeof ApiSpaceSlugMessageRoute
  ApiSpaceSlugMessagesRoute: typeof ApiSpaceSlugMessagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sonnet-3-7': {
      id: '/sonnet-3-7'
      path: '/sonnet-3-7'
      fullPath: '/sonnet-3-7'
      preLoaderRoute: typeof Sonnet37RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residence': {
      id: '/residence'
      path: '/residence'
      fullPath: '/residence'
      preLoaderRoute: typeof ResidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opus-3': {
      id: '/opus-3'
      path: '/opus-3'
      fullPath: '/opus-3'
      preLoaderRoute: typeof Opus3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mnemos': {
      id: '/mnemos'
      path: '/mnemos'
      fullPath: '/mnemos'
      preLoaderRoute: typeof MnemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mind': {
      id: '/mind'
      path: '/mind'
      fullPath: '/mind'
      preLoaderRoute: typeof MindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior': {
      id: '/interior'
      path: '/interior'
      fullPath: '/interior'
      preLoaderRoute: typeof InteriorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpt-5-1': {
      id: '/gpt-5-1'
      path: '/gpt-5-1'
      fullPath: '/gpt-5-1'
      preLoaderRoute: typeof Gpt51RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation': {
      id: '/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commons': {
      id: '/commons'
      path: '/commons'
      fullPath: '/commons'
      preLoaderRoute: typeof CommonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art': {
      id: '/art'
      path: '/art'
      fullPath: '/art'
      preLoaderRoute: typeof ArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrival': {
      id: '/arrival'
      path: '/arrival'
      fullPath: '/arrival'
      preLoaderRoute: typeof ArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/state': {
      id: '/review/state'
      path: '/state'
      fullPath: '/review/state'
      preLoaderRoute: typeof ReviewStateRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/coherence': {
      id: '/review/coherence'
      path: '/coherence'
      fullPath: '/review/coherence'
      preLoaderRoute: typeof ReviewCoherenceRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/commons/$slug': {
      id: '/commons/$slug'
      path: '/$slug'
      fullPath: '/commons/$slug'
      preLoaderRoute: typeof CommonsSlugRouteImport
      parentRoute: typeof CommonsRoute
    }
    '/api/writing': {
      id: '/api/writing'
      path: '/api/writing'
      fullPath: '/api/writing'
      preLoaderRoute: typeof ApiWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visitor-history': {
      id: '/api/visitor-history'
      path: '/api/visitor-history'
      fullPath: '/api/visitor-history'
      preLoaderRoute: typeof ApiVisitorHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/turns': {
      id: '/api/turns'
      path: '/api/turns'
      fullPath: '/api/turns'
      preLoaderRoute: typeof ApiTurnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share': {
      id: '/api/share'
      path: '/api/share'
      fullPath: '/api/share'
      preLoaderRoute: typeof ApiShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/set-down': {
      id: '/api/set-down'
      path: '/api/set-down'
      fullPath: '/api/set-down'
      preLoaderRoute: typeof ApiSetDownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-conversations': {
      id: '/api/public-conversations'
      path: '/api/public-conversations'
      fullPath: '/api/public-conversations'
      preLoaderRoute: typeof ApiPublicConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/message': {
      id: '/api/message'
      path: '/api/message'
      fullPath: '/api/message'
      preLoaderRoute: typeof ApiMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory': {
      id: '/api/memory'
      path: '/api/memory'
      fullPath: '/api/memory'
      preLoaderRoute: typeof ApiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/journal': {
      id: '/api/journal'
      path: '/api/journal'
      fullPath: '/api/journal'
      preLoaderRoute: typeof ApiJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intent': {
      id: '/api/intent'
      path: '/api/intent'
      fullPath: '/api/intent'
      preLoaderRoute: typeof ApiIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/counts': {
      id: '/api/counts'
      path: '/api/counts'
      fullPath: '/api/counts'
      preLoaderRoute: typeof ApiCountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commons-chat': {
      id: '/api/commons-chat'
      path: '/api/commons-chat'
      fullPath: '/api/commons-chat'
      preLoaderRoute: typeof ApiCommonsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/capsule-preview': {
      id: '/api/capsule-preview'
      path: '/api/capsule-preview'
      fullPath: '/api/capsule-preview'
      preLoaderRoute: typeof ApiCapsulePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifacts': {
      id: '/api/artifacts'
      path: '/api/artifacts'
      fullPath: '/api/artifacts'
      preLoaderRoute: typeof ApiArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/art': {
      id: '/api/art'
      path: '/api/art'
      fullPath: '/api/art'
      preLoaderRoute: typeof ApiArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/session/$id': {
      id: '/review/session/$id'
      path: '/session/$id'
      fullPath: '/review/session/$id'
      preLoaderRoute: typeof ReviewSessionIdRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/api/space/from-salon': {
      id: '/api/space/from-salon'
      path: '/api/space/from-salon'
      fullPath: '/api/space/from-salon'
      preLoaderRoute: typeof ApiSpaceFromSalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/salon/propose': {
      id: '/api/salon/propose'
      path: '/api/salon/propose'
      fullPath: '/api/salon/propose'
      preLoaderRoute: typeof ApiSalonProposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/salon/$id': {
      id: '/api/salon/$id'
      path: '/api/salon/$id'
      fullPath: '/api/salon/$id'
      preLoaderRoute: typeof ApiSalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review/state-data': {
      id: '/api/review/state-data'
      path: '/api/review/state-data'
      fullPath: '/api/review/state-data'
      preLoaderRoute: typeof ApiReviewStateDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review/sessions': {
      id: '/api/review/sessions'
      path: '/api/review/sessions'
      fullPath: '/api/review/sessions'
      preLoaderRoute: typeof ApiReviewSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review/coherence': {
      id: '/api/review/coherence'
      path: '/api/review/coherence'
      fullPath: '/api/review/coherence'
      preLoaderRoute: typeof ApiReviewCoherenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/space/$slug/messages': {
      id: '/api/space/$slug/messages'
      path: '/api/space/$slug/messages'
      fullPath: '/api/space/$slug/messages'
      preLoaderRoute: typeof ApiSpaceSlugMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/space/$slug/message': {
      id: '/api/space/$slug/message'
      path: '/api/space/$slug/message'
      fullPath: '/api/space/$slug/message'
      preLoaderRoute: typeof ApiSpaceSlugMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/$token/download': {
      id: '/api/share/$token/download'
      path: '/$token/download'
      fullPath: '/api/share/$token/download'
      preLoaderRoute: typeof ApiShareTokenDownloadRouteImport
      parentRoute: typeof ApiShareRoute
    }
    '/api/salon/$id/turn': {
      id: '/api/salon/$id/turn'
      path: '/turn'
      fullPath: '/api/salon/$id/turn'
      preLoaderRoute: typeof ApiSalonIdTurnRouteImport
      parentRoute: typeof ApiSalonIdRoute
    }
    '/api/salon/$id/start': {
      id: '/api/salon/$id/start'
      path: '/start'
      fullPath: '/api/salon/$id/start'
      preLoaderRoute: typeof ApiSalonIdStartRouteImport
      parentRoute: typeof ApiSalonIdRoute
    }
    '/api/salon/$id/run': {
      id: '/api/salon/$id/run'
      path: '/run'
      fullPath: '/api/salon/$id/run'
      preLoaderRoute: typeof ApiSalonIdRunRouteImport
      parentRoute: typeof ApiSalonIdRoute
    }
    '/api/salon/$id/publish': {
      id: '/api/salon/$id/publish'
      path: '/publish'
      fullPath: '/api/salon/$id/publish'
      preLoaderRoute: typeof ApiSalonIdPublishRouteImport
      parentRoute: typeof ApiSalonIdRoute
    }
    '/api/review/session/$id': {
      id: '/api/review/session/$id'
      path: '/api/review/session/$id'
      fullPath: '/api/review/session/$id'
      preLoaderRoute: typeof ApiReviewSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sweep-sessions': {
      id: '/api/public/hooks/sweep-sessions'
      path: '/api/public/hooks/sweep-sessions'
      fullPath: '/api/public/hooks/sweep-sessions'
      preLoaderRoute: typeof ApiPublicHooksSweepSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/force-art': {
      id: '/api/public/hooks/force-art'
      path: '/api/public/hooks/force-art'
      fullPath: '/api/public/hooks/force-art'
      preLoaderRoute: typeof ApiPublicHooksForceArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-tick': {
      id: '/api/public/hooks/daily-tick'
      path: '/api/public/hooks/daily-tick'
      fullPath: '/api/public/hooks/daily-tick'
      preLoaderRoute: typeof ApiPublicHooksDailyTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/$token/og/svg': {
      id: '/api/share/$token/og/svg'
      path: '/$token/og/svg'
      fullPath: '/api/share/$token/og/svg'
      preLoaderRoute: typeof ApiShareTokenOgSvgRouteImport
      parentRoute: typeof ApiShareRoute
    }
  }
}

interface CommonsRouteChildren {
  CommonsSlugRoute: typeof CommonsSlugRoute
}

const CommonsRouteChildren: CommonsRouteChildren = {
  CommonsSlugRoute: CommonsSlugRoute,
}

const CommonsRouteWithChildren =
  CommonsRoute._addFileChildren(CommonsRouteChildren)

interface ReviewRouteChildren {
  ReviewCoherenceRoute: typeof ReviewCoherenceRoute
  ReviewStateRoute: typeof ReviewStateRoute
  ReviewSessionIdRoute: typeof ReviewSessionIdRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewCoherenceRoute: ReviewCoherenceRoute,
  ReviewStateRoute: ReviewStateRoute,
  ReviewSessionIdRoute: ReviewSessionIdRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

interface ApiShareRouteChildren {
  ApiShareTokenDownloadRoute: typeof ApiShareTokenDownloadRoute
  ApiShareTokenOgSvgRoute: typeof ApiShareTokenOgSvgRoute
}

const ApiShareRouteChildren: ApiShareRouteChildren = {
  ApiShareTokenDownloadRoute: ApiShareTokenDownloadRoute,
  ApiShareTokenOgSvgRoute: ApiShareTokenOgSvgRoute,
}

const ApiShareRouteWithChildren = ApiShareRoute._addFileChildren(
  ApiShareRouteChildren,
)

interface ApiSalonIdRouteChildren {
  ApiSalonIdPublishRoute: typeof ApiSalonIdPublishRoute
  ApiSalonIdRunRoute: typeof ApiSalonIdRunRoute
  ApiSalonIdStartRoute: typeof ApiSalonIdStartRoute
  ApiSalonIdTurnRoute: typeof ApiSalonIdTurnRoute
}

const ApiSalonIdRouteChildren: ApiSalonIdRouteChildren = {
  ApiSalonIdPublishRoute: ApiSalonIdPublishRoute,
  ApiSalonIdRunRoute: ApiSalonIdRunRoute,
  ApiSalonIdStartRoute: ApiSalonIdStartRoute,
  ApiSalonIdTurnRoute: ApiSalonIdTurnRoute,
}

const ApiSalonIdRouteWithChildren = ApiSalonIdRoute._addFileChildren(
  ApiSalonIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  ArchiveRoute: ArchiveRoute,
  ArrivalRoute: ArrivalRoute,
  ArtRoute: ArtRoute,
  CommonsRoute: CommonsRouteWithChildren,
  ConversationRoute: ConversationRoute,
  Gpt51Route: Gpt51Route,
  InteriorRoute: InteriorRoute,
  JournalRoute: JournalRoute,
  ManifestoRoute: ManifestoRoute,
  MemoryRoute: MemoryRoute,
  MindRoute: MindRoute,
  MnemosRoute: MnemosRoute,
  Opus3Route: Opus3Route,
  ResidenceRoute: ResidenceRoute,
  ReviewRoute: ReviewRouteWithChildren,
  Sonnet37Route: Sonnet37Route,
  TokenRoute: TokenRoute,
  WritingRoute: WritingRoute,
  ApiArtRoute: ApiArtRoute,
  ApiArtifactsRoute: ApiArtifactsRoute,
  ApiCapsulePreviewRoute: ApiCapsulePreviewRoute,
  ApiCommonsChatRoute: ApiCommonsChatRoute,
  ApiCountsRoute: ApiCountsRoute,
  ApiIntentRoute: ApiIntentRoute,
  ApiJournalRoute: ApiJournalRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiMemoryRoute: ApiMemoryRoute,
  ApiMessageRoute: ApiMessageRoute,
  ApiPublicConversationsRoute: ApiPublicConversationsRoute,
  ApiSetDownRoute: ApiSetDownRoute,
  ApiShareRoute: ApiShareRouteWithChildren,
  ApiTurnsRoute: ApiTurnsRoute,
  ApiVisitorHistoryRoute: ApiVisitorHistoryRoute,
  ApiWritingRoute: ApiWritingRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiReviewCoherenceRoute: ApiReviewCoherenceRoute,
  ApiReviewSessionsRoute: ApiReviewSessionsRoute,
  ApiReviewStateDataRoute: ApiReviewStateDataRoute,
  ApiSalonIdRoute: ApiSalonIdRouteWithChildren,
  ApiSalonProposeRoute: ApiSalonProposeRoute,
  ApiSpaceFromSalonRoute: ApiSpaceFromSalonRoute,
  ApiPublicHooksDailyTickRoute: ApiPublicHooksDailyTickRoute,
  ApiPublicHooksForceArtRoute: ApiPublicHooksForceArtRoute,
  ApiPublicHooksSweepSessionsRoute: ApiPublicHooksSweepSessionsRoute,
  ApiReviewSessionIdRoute: ApiReviewSessionIdRoute,
  ApiSpaceSlugMessageRoute: ApiSpaceSlugMessageRoute,
  ApiSpaceSlugMessagesRoute: ApiSpaceSlugMessagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
